// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 1763 (Gilnid), 36 anchors over 545yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_1763()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 1763,
        {
            { -274.44f, -488.13f, 49.82f },
            { -281.04f, -505.07f, 49.36f },
            { -281.10f, -516.92f, 49.68f },
            { -280.98f, -507.75f, 49.45f },
            { -282.36f, -520.77f, 48.69f },
            { -293.11f, -530.05f, 50.38f },
            { -285.07f, -551.17f, 49.98f },
            { -297.42f, -573.46f, 49.06f },
            { -293.93f, -560.98f, 49.01f },
            { -299.08f, -583.29f, 47.16f },
            { -292.32f, -592.85f, 49.24f },
            { -276.16f, -587.70f, 50.42f },
            { -262.05f, -579.77f, 51.25f },
            { -269.50f, -581.47f, 50.54f },
            { -246.54f, -576.34f, 51.09f },
            { -231.25f, -585.74f, 20.05f },
            { -202.95f, -598.42f, 32.60f },
            { -221.77f, -592.34f, 21.73f },
            { -226.02f, -575.46f, 20.88f },
            { -208.73f, -599.14f, 28.96f },
            { -204.33f, -599.48f, 31.07f },
            { -215.90f, -595.80f, 25.31f },
            { -208.15f, -598.66f, 29.67f },
            { -217.42f, -595.09f, 23.90f },
            { -201.79f, -598.42f, 33.06f },
            { -209.72f, -598.77f, 28.70f },
            { -191.38f, -592.29f, 39.98f },
            { -205.51f, -598.68f, 31.29f },
            { -226.00f, -595.11f, 21.26f },
            { -205.02f, -598.87f, 31.49f },
            { -216.84f, -594.97f, 24.67f },
            { -212.33f, -576.92f, 21.56f },
            { -214.77f, -581.26f, 21.54f },
            { -212.34f, -577.40f, 21.18f },
            { -193.39f, -573.47f, 20.98f },
            { -185.37f, -572.40f, 20.72f },
        });
}
