// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 31 anchors over 464yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -16.40f, -383.07f, 61.78f },
            { -35.83f, -373.87f, 57.66f },
            { -52.53f, -368.77f, 55.39f },
            { -63.65f, -370.87f, 56.88f },
            { -58.44f, -377.21f, 54.93f },
            { -57.37f, -373.31f, 55.58f },
            { -52.43f, -371.10f, 56.44f },
            { -59.14f, -360.57f, 54.99f },
            { -63.79f, -384.16f, 54.02f },
            { -100.51f, -373.00f, 59.14f },
            { -95.95f, -379.53f, 59.06f },
            { -109.91f, -395.32f, 58.16f },
            { -121.63f, -389.84f, 59.41f },
            { -90.09f, -403.27f, 58.65f },
            { -98.78f, -390.28f, 58.58f },
            { -106.04f, -383.58f, 57.11f },
            { -126.24f, -392.19f, 58.81f },
            { -145.65f, -400.30f, 57.36f },
            { -153.90f, -402.31f, 56.99f },
            { -135.33f, -397.42f, 60.52f },
            { -143.65f, -400.70f, 58.52f },
            { -137.87f, -397.60f, 60.91f },
            { -158.20f, -403.21f, 57.62f },
            { -178.18f, -410.14f, 56.74f },
            { -182.15f, -410.86f, 56.17f },
            { -180.21f, -420.31f, 55.27f },
            { -188.98f, -439.57f, 54.29f },
            { -200.36f, -453.56f, 55.22f },
            { -184.79f, -448.87f, 55.38f },
            { -181.81f, -432.72f, 55.21f },
            { -180.76f, -427.05f, 55.71f },
        });
}
