// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 646 (Mr. Smite), 31 anchors over 487yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_646()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 646,
        {
            { -185.37f, -572.40f, 20.72f },
            { -188.04f, -552.49f, 19.31f },
            { -179.29f, -566.96f, 19.31f },
            { -161.64f, -580.04f, 19.32f },
            { -146.79f, -582.38f, 19.51f },
            { -139.19f, -581.90f, 18.88f },
            { -127.91f, -601.75f, 16.84f },
            { -133.25f, -611.28f, 14.59f },
            { -130.93f, -604.85f, 15.82f },
            { -126.96f, -624.66f, 13.11f },
            { -124.75f, -630.96f, 14.04f },
            { -113.48f, -619.85f, 14.30f },
            { -128.14f, -618.34f, 13.15f },
            { -121.08f, -637.95f, 12.22f },
            { -109.74f, -655.21f, 7.25f },
            { -102.34f, -671.76f, 7.41f },
            { -92.70f, -688.88f, 8.04f },
            { -91.75f, -684.76f, 8.00f },
            { -83.75f, -683.12f, 2.95f },
            { -76.33f, -702.59f, -4.50f },
            { -68.40f, -720.40f, -10.09f },
            { -60.35f, -739.82f, -7.32f },
            { -47.74f, -753.79f, -13.21f },
            { -24.61f, -771.93f, -5.34f },
            { -13.26f, -750.57f, 9.31f },
            { -4.66f, -769.36f, 9.83f },
            { -7.95f, -754.13f, 9.63f },
            { -9.15f, -748.57f, 9.67f },
            { -4.68f, -764.72f, 9.52f },
            { -7.04f, -753.88f, 9.56f },
            { -4.38f, -766.11f, 9.47f },
        });
}
