// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 16 anchors over 237yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -180.76f, -427.05f, 55.71f },
            { -191.03f, -458.51f, 54.52f },
            { -192.46f, -481.66f, 54.05f },
            { -188.98f, -497.71f, 53.90f },
            { -196.73f, -504.99f, 53.91f },
            { -189.83f, -496.88f, 54.25f },
            { -200.34f, -502.21f, 54.66f },
            { -189.83f, -495.07f, 53.93f },
            { -196.62f, -500.22f, 53.11f },
            { -215.21f, -498.20f, 49.57f },
            { -231.36f, -491.13f, 49.86f },
            { -258.43f, -486.03f, 49.44f },
            { -278.62f, -494.22f, 49.31f },
            { -270.10f, -487.58f, 50.02f },
            { -278.60f, -483.13f, 49.55f },
            { -275.87f, -486.41f, 49.60f },
        });
}
