#!/usr/bin/env bash
# Run one command inside the core build toolchain.
#
# WHY THIS EXISTS. ci.yml used to compile the tree twice on every push: once on
# the runner behind a warm ccache, and once inside `docker build` where the
# Dockerfile's ccache is a BuildKit cache mount and therefore not exported by
# type=gha. The second compile was 71 of the job's 77 minutes and started from
# zero every single time.
#
# The fix is to compile once, on the runner, and hand the finished install to
# the image. But the runner is Ubuntu 24.04 and the image is Debian trixie, and
# they disagree about the two libraries the server links hardest against: ACE
# (7.1.3 vs 8.0.2) and the MySQL client (libmysqlclient.so.21 vs libmariadb.so.3).
# A binary built on the runner installs into the image perfectly and then cannot
# exec. So the compile happens on the runner but *in a container* made from
# Dockerfile.core's `builder-base` stage - same Debian, same gcc, same sonames -
# with the ccache directory bind-mounted out to an ordinary path that
# actions/cache can carry between runs. That is the whole trick.
#
# The bind mounts, and why each one:
#   /src        the checkout. The build tree lives at /src/build so it survives
#               between invocations of this script - a container filesystem does
#               not, and ccache keys on the compile line, which includes paths.
#   /ccache     the compiler cache, on the host so it can be saved and restored.
#   /opt/turtle the staging directory. CMAKE_INSTALL_PREFIX is baked into the
#               binary as SYSCONFDIR, so `cmake --install` must write to the
#               real prefix; mounting the host's ./stage there is how the files
#               come back out without a DESTDIR that would falsify the prefix.
#
# --network host because the MariaDB service container is published on the
# runner's 127.0.0.1:3306 and the adapter suite connects to it, and because
# FetchContent clones googletest during configure.
#
# --user the runner's own uid so everything written through the bind mounts is
# owned by the runner and the later upload/artifact steps can read it.
#
# Usage:
#   bash ops/ci/in-builder.sh 'cmake --build /src/build --parallel "$(nproc)"'
#
# Invoked through `bash` rather than by its executable bit for the same reason
# every other script here is: this repository is developed on Windows and
# carries no executable bits.

set -euo pipefail

: "${BUILDER_IMAGE:?BUILDER_IMAGE is not set - the toolchain image was never built}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Created here rather than in the workflow so that a step calling this script
# directly does not need to remember to.
mkdir -p "$REPO_ROOT/.ccache" "$REPO_ROOT/stage"

# CCACHE_SLOPPINESS is not optional here. USE_PCH defaults to ON, and ccache
# refuses to cache a translation unit that includes a precompiled header unless
# pch_defines is allowed; the revision header also carries __DATE__/__TIME__,
# which is what time_macros is for. Without these the cache would report hits in
# the single digits and the 71 minutes would come straight back - which is why
# the build step prints `ccache --show-stats`.
#
# GIT_CONFIG_* below: the uid we run as is not in the image's /etc/passwd, and
# git refuses to read a repository it thinks belongs to somebody else. The
# revision header is generated by asking git for HEAD, so this is not optional.
exec docker run --rm \
    --network host \
    --user "$(id -u):$(id -g)" \
    --env HOME=/tmp \
    --env CCACHE_DIR=/ccache \
    --env CCACHE_MAXSIZE="${CCACHE_MAXSIZE:-4G}" \
    --env CCACHE_COMPRESS=1 \
    --env CCACHE_COMPRESSLEVEL=1 \
    --env CCACHE_SLOPPINESS=pch_defines,time_macros,include_file_mtime,include_file_ctime \
    --env GIT_CONFIG_COUNT=1 \
    --env GIT_CONFIG_KEY_0=safe.directory \
    --env GIT_CONFIG_VALUE_0='*' \
    --volume "$REPO_ROOT:/src" \
    --volume "$REPO_ROOT/.ccache:/ccache" \
    --volume "$REPO_ROOT/stage:/opt/turtle" \
    --workdir /src \
    "$BUILDER_IMAGE" \
    bash -c "$*"
