#!/usr/bin/env python3
"""Regenerate src/Routes/RecordedRoutes.cpp, the collector for recorded routes.

RecordedRoutes.cpp said "GENERATED by gen_routes.py - do not edit by hand" and
that generator was not in the tree. So it could not be re-run, it was not
re-run, and the collector went stale: it called 7 register functions while 97
route translation units defined one.

That is not a cosmetic drift. The collector's own comment explains the
consequence exactly:

    a translation unit whose only output is a function nobody calls contributes
    nothing, and the module is a static lib, so the linker drops it along with
    its route

So 90 recorded routes were compiled and then discarded at link time. Nothing
failed, nothing warned, and the bots simply did not have those routes. The disk
loader does not cover for it either: LoadRecordedRoutesFromDisk() reads
DungeonClear.RouteRecorderDir, which conf.dist does not set, and it is designed
to overlay routes recorded SINCE the build rather than to replace the compiled
set.

Run with --check to verify the collector is current without writing (this is
what CI does). Run with no arguments to rewrite it.

The mapping is entirely mechanical, verified across all 97 files:

    src/Routes/Route_<map>_<boss>.cpp  defines  RegisterRecordedRoute<map>_<boss>()
"""

import argparse
import pathlib
import re
import sys

ROUTES_SUBDIR = pathlib.Path("src") / "Routes"
COLLECTOR_NAME = "RecordedRoutes.cpp"

# Route_189_3977.cpp -> 189_3977. Anchored, so a stray file that merely starts
# with "Route_" cannot slip in with a garbage suffix.
ROUTE_FILE = re.compile(r"^Route_(\d+_\d+)\.cpp$")

HEADER = """// GENERATED by tools/gen_routes.py - do not edit by hand.
//
// One call per recorded route translation unit in src/Routes/. Without this
// collector the generated appenders never run: a translation unit whose only
// output is a function nobody calls contributes nothing, and the module is a
// static lib, so the linker drops it along with its route.
//
// Regenerate after adding or removing a recording:
//
//     python3 modules/mod-dungeon-clear/tools/gen_routes.py
//
// CI runs the same script with --check, so a new route that is never collected
// fails the build instead of silently not existing at runtime.
"""


def module_root() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent.parent


def route_ids(routes_dir: pathlib.Path) -> list[str]:
    """Every route id with a translation unit, sorted for a stable diff.

    Sorted numerically by (map, boss) rather than lexically, so 822 does not sit
    between 189 and 90 and make a regeneration look like a reshuffle.
    """
    ids = []
    for path in routes_dir.iterdir():
        match = ROUTE_FILE.match(path.name)
        if match:
            ids.append(match.group(1))
    return sorted(ids, key=lambda i: tuple(int(part) for part in i.split("_")))


def render(ids: list[str]) -> str:
    out = [HEADER]
    for route_id in ids:
        out.append(f"void RegisterRecordedRoute{route_id}();\n")
    out.append("\nvoid RegisterAllRecordedRoutes()\n{\n")
    for route_id in ids:
        out.append(f"    RegisterRecordedRoute{route_id}();\n")
    out.append("}\n")
    return "".join(out)


def verify_definitions(routes_dir: pathlib.Path, ids: list[str]) -> list[str]:
    """Confirm each file really defines the function its name implies.

    The generator asserts a naming convention; this checks the convention still
    holds rather than emitting a call to a symbol that does not exist, which
    would turn a silent runtime gap into a link error.
    """
    problems = []
    for route_id in ids:
        path = routes_dir / f"Route_{route_id}.cpp"
        wanted = re.compile(rf"\bvoid\s+RegisterRecordedRoute{route_id}\s*\(")
        if not wanted.search(path.read_text(encoding="utf-8", errors="replace")):
            problems.append(f"{path.name} does not define RegisterRecordedRoute{route_id}()")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the collector is out of date; write nothing")
    args = parser.parse_args()

    routes_dir = module_root() / ROUTES_SUBDIR
    if not routes_dir.is_dir():
        print(f"error: {routes_dir} is not a directory", file=sys.stderr)
        return 2

    ids = route_ids(routes_dir)
    if not ids:
        print(f"error: no Route_<map>_<boss>.cpp files under {routes_dir}", file=sys.stderr)
        return 2

    problems = verify_definitions(routes_dir, ids)
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 2

    collector = routes_dir / COLLECTOR_NAME
    wanted = render(ids)
    current = collector.read_text(encoding="utf-8") if collector.exists() else ""

    # Compare on normalised line endings: a CRLF checkout must not read as stale.
    if current.replace("\r\n", "\n") == wanted:
        print(f"{COLLECTOR_NAME} is up to date ({len(ids)} routes)")
        return 0

    if args.check:
        # Unique names, not raw matches: each route appears twice in the file,
        # once as a declaration and once as a call, and reporting "14 routes"
        # when it collects 7 sends the reader looking for the wrong thing.
        have = len(set(re.findall(r"RegisterRecordedRoute(\d+_\d+)\(\);", current)))
        print(f"error: {COLLECTOR_NAME} is stale - it collects {have} routes, "
              f"but {len(ids)} translation units define one.", file=sys.stderr)
        print("       Routes it does not collect are dropped by the linker and do "
              "not exist at runtime.", file=sys.stderr)
        print("       Fix: python3 modules/mod-dungeon-clear/tools/gen_routes.py",
              file=sys.stderr)
        return 1

    collector.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"wrote {COLLECTOR_NAME} ({len(ids)} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
