// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62068 (Slagfist Destroyer), 32 anchors over 457yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62068()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62068,
        {
            { -6291.23f, -4099.47f, 265.39f },
            { -6287.50f, -4109.89f, 265.40f },
            { -6292.62f, -4126.40f, 265.06f },
            { -6284.38f, -4142.15f, 265.79f },
            { -6281.55f, -4151.36f, 265.79f },
            { -6286.75f, -4170.72f, 265.79f },
            { -6286.48f, -4189.24f, 265.77f },
            { -6288.15f, -4206.52f, 265.30f },
            { -6288.41f, -4214.62f, 265.60f },
            { -6311.31f, -4220.97f, 264.84f },
            { -6324.97f, -4235.10f, 265.20f },
            { -6316.61f, -4249.85f, 265.50f },
            { -6325.98f, -4250.11f, 266.31f },
            { -6331.62f, -4257.29f, 266.33f },
            { -6330.56f, -4274.65f, 266.60f },
            { -6327.76f, -4291.29f, 266.28f },
            { -6345.26f, -4299.96f, 266.61f },
            { -6366.07f, -4298.86f, 266.25f },
            { -6383.01f, -4293.46f, 265.35f },
            { -6401.32f, -4289.37f, 263.74f },
            { -6417.95f, -4286.63f, 263.69f },
            { -6436.80f, -4282.77f, 263.65f },
            { -6444.45f, -4279.85f, 263.10f },
            { -6450.46f, -4272.21f, 259.27f },
            { -6455.51f, -4265.70f, 255.37f },
            { -6463.35f, -4262.09f, 250.74f },
            { -6471.28f, -4262.60f, 245.76f },
            { -6479.50f, -4264.07f, 240.63f },
            { -6488.79f, -4261.69f, 237.81f },
            { -6498.31f, -4247.55f, 236.90f },
            { -6510.17f, -4235.48f, 235.03f },
            { -6524.26f, -4226.84f, 233.35f },
        });
}
