// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 18 anchors over 239yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -192.51f, -443.35f, 54.56f },
            { -190.41f, -463.63f, 54.34f },
            { -187.62f, -479.02f, 54.60f },
            { -185.67f, -486.13f, 54.58f },
            { -188.84f, -475.11f, 54.61f },
            { -192.85f, -474.95f, 54.17f },
            { -197.01f, -496.95f, 53.65f },
            { -201.11f, -506.92f, 53.47f },
            { -216.82f, -501.24f, 50.33f },
            { -219.03f, -491.26f, 48.98f },
            { -214.01f, -494.06f, 51.08f },
            { -222.18f, -499.18f, 50.56f },
            { -230.52f, -494.39f, 50.90f },
            { -231.38f, -478.29f, 49.23f },
            { -243.49f, -487.97f, 49.82f },
            { -264.93f, -487.66f, 49.66f },
            { -284.32f, -497.15f, 49.95f },
            { -267.67f, -484.64f, 49.92f },
        });
}
