// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 1763 (Gilnid), 35 anchors over 460yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_1763()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 1763,
        {
            { -279.29f, -505.48f, 50.20f },
            { -284.69f, -503.83f, 49.96f },
            { -288.35f, -523.82f, 49.90f },
            { -288.16f, -547.05f, 49.51f },
            { -287.36f, -552.94f, 49.52f },
            { -297.33f, -570.36f, 49.33f },
            { -306.42f, -585.60f, 48.26f },
            { -299.23f, -574.28f, 48.04f },
            { -293.00f, -603.72f, 48.10f },
            { -278.15f, -588.86f, 50.05f },
            { -273.87f, -576.38f, 50.78f },
            { -272.10f, -580.42f, 50.66f },
            { -281.58f, -590.69f, 52.07f },
            { -264.43f, -582.72f, 50.86f },
            { -240.27f, -580.11f, 19.67f },
            { -233.94f, -582.58f, 19.99f },
            { -240.76f, -578.22f, 19.86f },
            { -226.70f, -588.91f, 20.55f },
            { -236.76f, -581.58f, 19.88f },
            { -219.56f, -593.28f, 22.69f },
            { -197.70f, -597.14f, 35.53f },
            { -203.46f, -598.52f, 32.36f },
            { -216.72f, -591.98f, 22.41f },
            { -213.09f, -597.79f, 26.73f },
            { -214.85f, -591.48f, 21.98f },
            { -222.94f, -590.54f, 21.33f },
            { -207.33f, -586.88f, 21.56f },
            { -210.71f, -589.42f, 21.56f },
            { -207.49f, -585.05f, 21.56f },
            { -221.31f, -581.62f, 21.48f },
            { -218.84f, -595.03f, 22.72f },
            { -222.91f, -592.07f, 21.75f },
            { -224.29f, -583.68f, 19.50f },
            { -208.01f, -580.54f, 19.46f },
            { -193.60f, -578.48f, 19.55f },
        });
}
