// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 39 anchors over 520yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -27.55f, -377.40f, 60.13f },
            { -36.63f, -373.07f, 58.28f },
            { -54.77f, -376.22f, 54.32f },
            { -63.77f, -384.07f, 54.12f },
            { -60.01f, -381.67f, 54.59f },
            { -52.48f, -384.90f, 55.18f },
            { -56.64f, -379.58f, 54.85f },
            { -49.98f, -391.19f, 56.86f },
            { -54.78f, -385.09f, 54.74f },
            { -47.25f, -385.48f, 56.15f },
            { -49.56f, -380.42f, 54.89f },
            { -64.79f, -379.26f, 54.06f },
            { -80.88f, -377.55f, 56.29f },
            { -98.28f, -383.23f, 59.21f },
            { -98.48f, -374.33f, 59.60f },
            { -97.78f, -378.38f, 59.16f },
            { -93.17f, -378.33f, 58.47f },
            { -120.92f, -384.79f, 59.35f },
            { -131.76f, -394.60f, 60.37f },
            { -125.64f, -388.34f, 60.00f },
            { -109.60f, -400.51f, 59.56f },
            { -86.84f, -399.88f, 59.39f },
            { -102.60f, -404.55f, 59.52f },
            { -95.48f, -402.43f, 57.98f },
            { -114.83f, -407.48f, 59.74f },
            { -130.23f, -396.79f, 59.15f },
            { -145.10f, -403.38f, 57.81f },
            { -158.69f, -400.53f, 57.25f },
            { -141.47f, -401.94f, 58.83f },
            { -134.99f, -401.37f, 59.07f },
            { -146.81f, -397.99f, 58.33f },
            { -136.53f, -398.12f, 58.34f },
            { -161.81f, -404.27f, 58.63f },
            { -178.86f, -410.75f, 55.91f },
            { -170.30f, -406.61f, 57.13f },
            { -185.05f, -432.54f, 54.04f },
            { -189.50f, -440.97f, 54.40f },
            { -182.67f, -450.07f, 55.25f },
            { -202.61f, -454.44f, 55.02f },
        });
}
