// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 646 (Mr. Smite), 24 anchors over 910yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_646()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 646,
        {
            { -103.49f, -577.27f, 51.76f },
            { -142.33f, -577.51f, 19.28f },
            { -164.74f, -579.70f, 19.31f },
            { -186.00f, -581.78f, 20.76f },
            { -208.18f, -588.97f, 20.98f },
            { -212.43f, -590.47f, 20.98f },
            { -184.39f, -581.52f, 20.66f },
            { -167.22f, -580.34f, 19.32f },
            { -135.09f, -589.97f, 18.66f },
            { -129.46f, -612.30f, 13.84f },
            { -124.02f, -634.10f, 12.92f },
            { -111.05f, -651.03f, 7.35f },
            { -99.81f, -670.82f, 7.42f },
            { -84.57f, -679.94f, 2.58f },
            { -77.99f, -699.41f, -2.73f },
            { -70.16f, -716.79f, -11.35f },
            { -62.01f, -735.81f, -7.02f },
            { -49.94f, -751.91f, -12.47f },
            { -33.92f, -766.34f, -10.69f },
            { -17.24f, -775.85f, -2.46f },
            { -4.92f, -781.37f, 10.12f },
            { -22.03f, -800.52f, 12.76f },
            { -23.53f, -818.76f, 12.39f },
            { -14.57f, -385.48f, 62.46f },
        });
}
