// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62069 (Halgan Redbrand), 13 anchors over 213yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62069()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62069,
        {
            { -6539.19f, -4206.34f, 231.17f },
            { -6547.99f, -4189.94f, 230.20f },
            { -6556.16f, -4173.09f, 229.68f },
            { -6563.57f, -4157.39f, 229.20f },
            { -6566.83f, -4138.76f, 229.03f },
            { -6571.17f, -4122.09f, 228.96f },
            { -6574.26f, -4103.79f, 227.68f },
            { -6578.27f, -4087.64f, 225.61f },
            { -6582.64f, -4071.10f, 223.48f },
            { -6586.94f, -4054.66f, 221.36f },
            { -6591.56f, -4036.07f, 218.97f },
            { -6593.52f, -4018.97f, 216.88f },
            { -6594.38f, -4001.76f, 216.93f },
        });
}
