// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 816, boss 62066 (Cavernweb Broodmother), 16 anchors over 250yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute816_62066()
{
    DungeonClearRouteRegistry::Register(816, DUNGEON_DIFFICULTY_NORMAL, 62066,
        {
            { -6288.37f, -4051.74f, 73.22f },
            { -6287.50f, -4035.09f, 72.60f },
            { -6287.46f, -4015.76f, 72.60f },
            { -6287.16f, -3996.74f, 72.60f },
            { -6286.15f, -3979.37f, 72.60f },
            { -6283.34f, -3971.43f, 72.60f },
            { -6269.04f, -3961.92f, 72.60f },
            { -6254.46f, -3952.92f, 72.60f },
            { -6236.76f, -3949.63f, 72.60f },
            { -6220.43f, -3948.03f, 72.60f },
            { -6201.83f, -3942.76f, 72.60f },
            { -6184.12f, -3937.37f, 72.60f },
            { -6167.46f, -3943.17f, 72.60f },
            { -6148.17f, -3950.29f, 72.69f },
            { -6132.93f, -3956.82f, 72.60f },
            { -6125.54f, -3960.76f, 72.60f },
        });
}
