[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$Root='C:\TW\ComTW\runbooks\ssc-ollama-manual-scaling-01-phase1-20260829-210352';$Ev=Join-Path $Root 'evidence';$Repo='C:\TW\ComTW\source';$Conf='C:\TW\ComTW\server\aiplayerbot.conf'
function W([string]$p,[string]$c){if(Test-Path $p){throw "Refusing overwrite $p"};[IO.File]::WriteAllText($p,$c,[Text.UTF8Encoding]::new($false))}
function G([string[]]$a){$o=& git -c safe.directory=C:/TW/ComTW/source -C $Repo @a 2>&1;if($LASTEXITCODE-ne 0){throw ($o-join"`n")};$o-join"`n"}
function Map([string]$p){$m=[ordered]@{};foreach($l in [IO.File]::ReadAllLines($p)){$t=$l.Trim();if(!$t-or$t.StartsWith('#')-or$t.StartsWith(';')){continue};$i=$t.IndexOf('=');if($i-gt 0){$m[$t.Substring(0,$i).Trim()]=$t.Substring($i+1).Trim()}};$m}
$before=(Get-FileHash $Conf -Algorithm SHA256).Hash;$item=Get-Item $Conf;$m=Map $Conf
$keys=@('AiPlayerbot.Enabled','AiPlayerbot.BotAutologin','AiPlayerbot.RandomBotAutologin','AiPlayerbot.RandomBotLoginAtStartup','AiPlayerbot.MinRandomBots','AiPlayerbot.MaxRandomBots','AiPlayerbot.RandomBotsMaxLoginsPerInterval','AiPlayerbot.AsyncBotLogin','AiPlayerbot.RandomBotLoginWithPlayer','AiPlayerbot.PinnedBots','AiPlayerbot.LLMEnabled','AiPlayerbot.LLMGlobalContext','AiPlayerbot.LLMBotToBotChatChance','AiPlayerbot.LLMRpgAIChatChance','AiPlayerbot.LLMBlockedReplyChannels','AiPlayerbot.LLMDefaultPromptsFile','AiPlayerbot.RandomBotSayWithoutMaster','AiPlayerbot.InviteChat')
$vals=[ordered]@{};foreach($k in $keys){$vals[$k]=if($m.Contains($k)){$m[$k]}else{$null}}
$endpoint=$m['AiPlayerbot.LLMApiEndpoint'];$api=$m['AiPlayerbot.LLMApiKey']
$e=[ordered]@{path=$item.FullName;size_bytes=$item.Length;last_write_utc=$item.LastWriteTimeUtc.ToString('o');sha256=$before;selected_explicit_values=$vals;effective_defaults_for_omitted=[ordered]@{'AiPlayerbot.LLMGlobalContext'='0 (PlayerbotAIConfig.cpp:772)';'AiPlayerbot.LLMBlockedReplyChannels'='empty list (PlayerbotAIConfig.cpp:776-796)';'AiPlayerbot.PinnedBots'='empty list (PlayerbotAIConfig.cpp:298)';'AiPlayerbot.RandomBotLoginWithPlayer'='0 (PlayerbotAIConfig.cpp:362)'};llm_endpoint=$endpoint;llm_api_key_empty=([string]::IsNullOrEmpty($api));llm_api_key_sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes([string]$api)));default_prompts_resolved_path=(Join-Path 'C:\TW\ComTW\server' ([string]$m['AiPlayerbot.LLMDefaultPromptsFile']));default_prompts_file_exists=(Test-Path -LiteralPath (Join-Path 'C:\TW\ComTW\server' ([string]$m['AiPlayerbot.LLMDefaultPromptsFile'])));recognized_block_tokens=@('guild','world','general','trade','lfg','ldefence','wdefence','grecruitement','say','whisper','emote','temote','yell','party','raid');whisper_only_block_tokens=@('guild','world','general','trade','lfg','ldefence','wdefence','grecruitement','say','emote','temote','yell','party','raid')}
W (Join-Path $Ev 'active-aiplayerbot-config-evidence.json') (($e|ConvertTo-Json -Depth 8)+"`n")
$head=(G @('rev-parse','HEAD')).Trim();$tree=(G @('rev-parse','HEAD^{tree}')).Trim();$status=G @('status','--short','--untracked-files=all');$paths=@('src/modules/PlayerBots/playerbot/PlayerbotAIConfig.cpp','src/modules/PlayerBots/playerbot/RandomPlayerbotMgr.cpp','src/modules/PlayerBots/playerbot/PlayerbotMgr.cpp','src/modules/PlayerBots/playerbot/strategy/actions/SayAction.cpp','src/modules/PlayerBots/playerbot/strategy/triggers/RpgTriggers.cpp','src/game/SharedDefines.h')
$files=@();foreach($p in $paths){& git -c safe.directory=C:/TW/ComTW/source -C $Repo diff --quiet HEAD -- $p;$differs=($LASTEXITCODE-ne 0);$files += [pscustomobject][ordered]@{path=$p;head_blob=(G @('rev-parse',"HEAD:$p")).Trim();working_file_sha256=(Get-FileHash (Join-Path $Repo ($p-replace'/','\')) -Algorithm SHA256).Hash;working_differs_from_head=$differs}}
$s=[ordered]@{repository=$Repo;head=$head;tree=$tree;status_short=$status;relevant_files=$files;analysis_basis='HEAD content for excerpts; relevant working files verified against HEAD'};W (Join-Path $Ev 'source-identity.json') (($s|ConvertTo-Json -Depth 7)+"`n")
$specs=@(
  [pscustomobject]@{p='src/modules/PlayerBots/playerbot/PlayerbotAIConfig.cpp';ranges=@(@(246,250),@(294,310),@(340,340),@(362,363),@(705,718),@(772,800),@(1365,1372))},
  [pscustomobject]@{p='src/modules/PlayerBots/playerbot/RandomPlayerbotMgr.cpp';ranges=@(@(644,704),@(724,773),@(1121,1133),@(1261,1300),@(1992,2055),@(2232,2283),@(3456,3473))},
  [pscustomobject]@{p='src/modules/PlayerBots/playerbot/PlayerbotMgr.cpp';ranges=@(@(823,866),@(908,942),@(1022,1074),@(2105,2151))},
  [pscustomobject]@{p='src/modules/PlayerBots/playerbot/strategy/actions/SayAction.cpp';ranges=@(@(512,515),@(602,655))},
  [pscustomobject]@{p='src/modules/PlayerBots/playerbot/strategy/triggers/RpgTriggers.cpp';ranges=@(@(627,639))},
  [pscustomobject]@{p='src/game/SharedDefines.h';ranges=@(@(1168,1172))}
)
$out=[Collections.Generic.List[string]]::new();foreach($sp in $specs){$out.Add("===== $($sp.p) @ $head =====");$lines=(G @('show',"HEAD:$($sp.p)"))-split"`n";foreach($r in $sp.ranges){$out.Add("--- $($r[0])-$($r[1]) ---");for($i=$r[0]-1;$i-lt[Math]::Min($r[1],$lines.Count);$i++){$out.Add(('{0,6}: {1}'-f($i+1),$lines[$i]))}}};W (Join-Path $Ev 'source-control-flow-excerpts.txt') (($out-join"`n")+"`n")
$after=(Get-FileHash $Conf -Algorithm SHA256).Hash;W (Join-Path $Ev 'phase1-readonly-integrity.json') (([ordered]@{config_sha256_before=$before;config_sha256_after=$after;config_unchanged=($before-eq$after);database_statement_class='SELECT only';source_or_config_writes=@();bot_login_actions=@();process_control_actions=@()}|ConvertTo-Json -Depth 5)+"`n")
Write-Output 'Source/config evidence captured.'
