[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$Root='C:\TW\ComTW\runbooks\ssc-ollama-manual-scaling-01-phase1-20260829-210352';$Ev=Join-Path $Root 'evidence';$Cfg='C:\TW\ComTW\server\mangosd.conf';$Client='C:\TW\ComTW\DB\bin\mariadb.exe'
$SqlPath=Join-Path $Ev 'bot-candidate-selects.sql';$OutPath=Join-Path $Ev 'bot-candidate-selects.stdout.txt';$ErrPath=Join-Path $Ev 'bot-candidate-selects.stderr.txt';$MetaPath=Join-Path $Ev 'bot-candidate-selects.metadata.json'
foreach($p in @($SqlPath,$OutPath,$ErrPath,$MetaPath)){if(Test-Path -LiteralPath $p){throw "Refusing to overwrite $p"}}
function CV([string]$k){foreach($line in [IO.File]::ReadAllLines($Cfg)){$t=$line.Trim();if(!$t-or$t.StartsWith('#')-or$t.StartsWith(';')){continue};$i=$t.IndexOf('=');if($i-gt 0-and$t.Substring(0,$i).Trim()-eq$k){return $t.Substring($i+1).Trim().Trim('"')}};throw "Missing $k"}
$sql=@"
SELECT 'SECTION','GROUP_SIDE_PATH';
SELECT COUNT(DISTINCT gm.groupId),COUNT(DISTINCT gm.memberGuid),SUM(leader_account.username LIKE 'RNDBOT%'),SUM(leader_account.username NOT LIKE 'RNDBOT%') FROM tw_char.group_member gm JOIN tw_char.characters member_char ON member_char.guid=gm.memberGuid JOIN tw_logon.account member_account ON member_account.id=member_char.account JOIN tw_char.groups g ON g.groupId=gm.groupId JOIN tw_char.characters leader_char ON leader_char.guid=g.leaderGuid JOIN tw_logon.account leader_account ON leader_account.id=leader_char.account WHERE member_account.username LIKE 'RNDBOT%';
SELECT 'SECTION','GROUP_SIDE_PATH_DETAILS_REDACTED';
SELECT gm.groupId,member_char.guid,member_char.name,member_char.online,IF(leader_account.username LIKE 'RNDBOT%','RNDBOT_LEADER','NON_RNDBOT_LEADER') FROM tw_char.group_member gm JOIN tw_char.characters member_char ON member_char.guid=gm.memberGuid JOIN tw_logon.account member_account ON member_account.id=member_char.account JOIN tw_char.groups g ON g.groupId=gm.groupId JOIN tw_char.characters leader_char ON leader_char.guid=g.leaderGuid JOIN tw_logon.account leader_account ON leader_account.id=leader_char.account WHERE member_account.username LIKE 'RNDBOT%' ORDER BY gm.groupId,member_char.guid;
SELECT 'SECTION','CANDIDATES';
SELECT c.guid,c.name,c.account,a.username,c.race,c.class,c.level,c.online,COALESCE(ev.add_value,0),COALESCE(ev.login_value,0),IF(gm.memberGuid IS NULL,0,1),GROUP_CONCAT(CONCAT(cs.skill,':',cs.value,'/',cs.max) ORDER BY cs.skill SEPARATOR ',') FROM tw_char.characters c JOIN tw_logon.account a ON a.id=c.account LEFT JOIN (SELECT bot,MAX(IF(event='add',value,0)) add_value,MAX(IF(event='login',value,0)) login_value FROM tw_char.ai_playerbot_random_bots WHERE owner=0 GROUP BY bot) ev ON ev.bot=c.guid LEFT JOIN tw_char.group_member gm ON gm.memberGuid=c.guid LEFT JOIN tw_char.character_skills cs ON cs.guid=c.guid AND cs.skill IN (164,165,171,182,186,197,202,333,393) WHERE a.username LIKE 'RNDBOT%' AND c.online=0 AND COALESCE(ev.add_value,0)=0 AND COALESCE(ev.login_value,0)=0 AND gm.memberGuid IS NULL GROUP BY c.guid,c.name,c.account,a.username,c.race,c.class,c.level,c.online,ev.add_value,ev.login_value,gm.memberGuid HAVING COUNT(cs.skill)>=1 ORDER BY c.level DESC,COUNT(cs.skill) DESC,c.guid LIMIT 50;
"@
[IO.File]::WriteAllText($SqlPath,$sql,[Text.UTF8Encoding]::new($false));$d=(CV 'LoginDatabase.Info')-split ';';$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=$Client;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true
foreach($a in @('--no-defaults','--protocol=TCP','--skip-ssl','--connect-timeout=3','--batch','--raw','--skip-column-names',('--host='+$d[0]),('--port='+$d[1]),('--user='+$d[2]),('--execute='+$sql))){[void]$psi.ArgumentList.Add($a)};$psi.Environment['MYSQL_PWD']=$d[3]
$p=[Diagnostics.Process]::new();$p.StartInfo=$psi;$start=[DateTime]::UtcNow;[void]$p.Start();$stdout=$p.StandardOutput.ReadToEnd();$stderr=$p.StandardError.ReadToEnd();$p.WaitForExit();$stderr=$stderr-replace[regex]::Escape($d[3]),'<redacted>'
[IO.File]::WriteAllText($OutPath,$stdout,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText($ErrPath,$stderr,[Text.UTF8Encoding]::new($false));$m=[ordered]@{statement_class='SELECT only';sql_sha256=(Get-FileHash $SqlPath -Algorithm SHA256).Hash;started_utc=$start.ToString('o');finished_utc=[DateTime]::UtcNow.ToString('o');exit_code=$p.ExitCode;stdout_sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($stdout)));stdout_size_bytes=[Text.Encoding]::UTF8.GetByteCount($stdout);stderr=$stderr;database_writes=@();credentials_emitted=$false};[IO.File]::WriteAllText($MetaPath,($m|ConvertTo-Json -Depth 5)+"`n",[Text.UTF8Encoding]::new($false));$m|ConvertTo-Json;if($p.ExitCode-ne 0){exit $p.ExitCode}
