"""Client facts as SQL predicates for ``ops/dbcheck``: ids and tile numbers only, no client content.

Two facts are derived from the client and written as a dbcheck rule file (``[macro]`` entries):

* ``go_display_known``: the GameObjectDisplayInfo ids the client's DBC knows, as ``BETWEEN`` ranges;
* ``client_tiles_map<N>``: the ADT tiles the client has for a continent (non-empty after all patches),
  as ranges of ``tile id = x * 1000 + y`` with x from the world Y axis and y from the world X axis.

The rules that use them live in ``ops/dbcheck/rules/client.toml``; this module only produces the
numbers, so they can be regenerated when the client changes.
"""

from __future__ import annotations

from datetime import date

from . import archives, maps
from .dbcraw import read_raw


def compress(values) -> list[tuple[int, int]]:
    """Sorted, merged inclusive ranges of the given integers."""
    out: list[tuple[int, int]] = []
    for v in sorted(set(values)):
        if out and v == out[-1][1] + 1:
            out[-1] = (out[-1][0], v)
        else:
            out.append((v, v))
    return out


def predicate(expr: str, ranges: list[tuple[int, int]]) -> str:
    """``expr BETWEEN a AND b OR ...``; a single id becomes ``expr = a``."""
    if not ranges:
        return "1 = 0"
    parts = [f"{expr} = {a}" if a == b else f"{expr} BETWEEN {a} AND {b}" for a, b in ranges]
    return "\n OR ".join(parts)


def tile_ids(cmaps: dict, directory: str) -> list[int]:
    return [x * 1000 + y for (x, y) in cmaps.get(directory.lower(), {"tiles": {}})["tiles"]]


def render(go_display_ids, tiles_by_map: dict[int, list[int]], source: str, on: str | None = None) -> str:
    on = on or date.today().isoformat()
    lines = [
        "# Generated by `python -m clientinventory facts` -- do not edit by hand.",
        f"# Source: {source}; date {on}. Numbers only (display ids, tile numbers); no client content.",
        "# go_display_known: GameObjectDisplayInfo ids the client knows (use with alias t.displayId).",
        "# client_tiles_map<N>: tile ids x*1000+y of the non-empty ADT tiles the client has for map N (alias s.tid).",
        "",
        "[macro]",
        'go_display_known = """',
        predicate("t.displayId", compress(go_display_ids)),
        '"""',
    ]
    for mid in sorted(tiles_by_map):
        lines += [f"client_tiles_map{mid} = \"\"\"", predicate("s.tid", compress(tiles_by_map[mid])), '"""']
    return "\n".join(lines) + "\n"


def build(dbc_dir, data_dir, lists_dir, map_dirs: dict[int, str]) -> tuple[list[int], dict[int, list[int]]]:
    display = [r[0] for r in read_raw(dbc_dir / "GameObjectDisplayInfo.dbc").rows]
    lists = archives.load_listings(lists_dir)
    eff = archives.effective_map_files(data_dir, lists)
    cmaps = maps.client_maps(lists, eff)
    return display, {mid: tile_ids(cmaps, d) for mid, d in map_dirs.items()}
